build: off
version: "0.1.0-{build}"

image:
  - macOS
  - Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - PYTHON_WIN: "C:\\Python38-x64"
      PYTHON_MAC: "venv3.9.1"
      PYTHON_UBU: "venv3.9/bin/python"
      PYTHON_VERSION: "3.9.1"
      PYTHON_ARCH: "64"


for:
  - 
    matrix:
      only:
        - image: Visual Studio 2019
    init:
      - "ECHO %PYTHON_WIN% %PYTHON_VERSION% %PYTHON_ARCH%"
      - "%PYTHON_WIN%\\python.exe --version"

    install:
      - "git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git"
      - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"
      - "SET PYVISTA_OFF_SCREEN=True"
      - "%PYTHON_WIN%\\python.exe -m pip install -r requirements.txt"
      - "%PYTHON_WIN%\\python.exe -m pip install cx_freeze"
      - "%PYTHON_WIN%\\python.exe -m pip install ."
      - "%PYTHON_WIN%\\python.exe cx_freeze_setup.py bdist_msi"
      - ps: "ls"

    artifacts:
      path: dist/*.msi
      name: Windows App
        
  -
    matrix:
      only:
        - image: macOS
    
    init:
      - "ls"
      - "echo $PYTHON_MAC $PYTHON_VERSION $PYTHON_ARCH"
      - "$HOME/$PYTHON_MAC/bin/python --version"
    
    install:
      - "$HOME/$PYTHON_MAC/bin/python -m pip install -r requirements.txt"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install cx_freeze"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install ."
      - "$HOME/$PYTHON_MAC/bin/python cx_freeze_setup.py bdist_mac --iconfile icon.icns --bundle-name=yttt --custom-info-plist Info.plist -q"
      - "npm i -g create-dmg"
      - "cd build"
      - "create-dmg yttt.app || true"
      - "mv \"yttt undefined.dmg\" yttt-$APPVEYOR_REPO_TAG_NAME-macos.dmg"
      - "ls"
      - "cd ../"

    artifacts:
      path: build/*.dmg
      name: Mac App
